### PR TITLE
ROOT6 compatibility

### PR DESCRIPTION
**Pull request by gpronost**
Modified CMakeLists : still compatible with ROOT5
Modified make/env scripts for sukap
Modified LinkDef (missing lines were causing crash when reading the root output with ROOT6)

### CODE REVIEW

**Comment by gpronost** [comment]
- I also modified the way the flat TTree was defined in RunAction code, this was causing a huge bunch of warning since the syntax is not correct.
- Note: ROOT5 is still default in the sukap scripts

**Comment by bquilain** [comment]
Thank you very much Guillaume, that will really be a blessing. It is a bit late now, but I will definitely check this tomorrow!

**Comment by bquilain** [comment]
It seems perfectly fine to go. As you, I also encounted trouble with the way cherenkov hits are accessed and had to solve it with the following you proposed:
  if(pmtType==0) wcsimrootcherenkovhit = (WCSimRootCherenkovHit*) (wcsimrootevent->GetCherenkovHits())->At(i);
as some of my student tried to compile with ROOT6.

I will merge now, and test it thouroughly. Thank you very much

**Comment by bquilain** [comment]
I checked, and had no issue for compilation in ROOT5 and ROOT6. I also tried to run a script, it worked perfectly. I will do more thourough check avec next update (adding possibility to modify mPMT coverage in mac file).
Thank you very much Guillaume

**Pull request merged**
