### PR TITLE
Geo update

### PR DESCRIPTION
**Pull request by gpronost**
Add some functions in RootGeom to improve compatibility with the official WCSim (needed for hk-AstroAnalysis and TriggerApplication)

### CODE REVIEW

**Comment by gpronost** [comment]
Izumiyama-san pull request should go first (it's more important). There will likely be some conflicts after but I will solve them.

**Comment by bquilain** [comment]
It seems very nice to go. The few changes you made in the geometry output may requires a bit of work on the fiTQun side, so I have to slightly modify the WCSimWrapper in it (and I would rather do it after fiTQun is tuned if possible). As it is not urgent, would it be fine to wait a bit before merging?

**Comment by gpronost** [comment]
I don't know how is the fitQun WCSimWrapper so I don't really know. The way ID PMT and mPMT are stored doesn't change, and the functions used to access them don't change too, there are just additional features. Code which was compatible with the previous version will still be compatible without any change required (except re-compilation). Recompiling fitQun with this new version may be enough I think.

But again, I don't how work fitQun WCSimWrapper so I may be wrong.

Anyway it's fine to wait, but we will need this for hk-AstroAnalysis (and TriggerApplication) so it depends how long you want to wait.

**Review by bquilain — COMMENTED** [review]
Sorry for delay Guillaume. I checked your proposal, and there is nothing that would conflict with WCSimWrapper (maybe it will just map const int into int, but this is all).
It is ready to go!

**Comment by gpronost** [comment]
Thanks!

**Pull request merged**
