### PR TITLE
Radon hybrid

### PR DESCRIPTION
**Pull request by gpronost**
There was modification in the way the PMT hit time are sorted, and of the PhysicsList we should test if it's still working as expected for other simulations.

I did a modification in src/WCSimWCAddDarkNoise.cc line 105:
I replaced: 
`WCSimWCTriggerBase *WCTM = (WCSimWCTriggerBase *) DigiMan->FindDigitizerModule("WCReadoutPMT2");
`
by: 
`WCSimWCTriggerBase *WCTM = (WCSimWCTriggerBase *) DigiMan->FindDigitizerModule("WCReadout2");
`
I think it was a bug to use "WCReadoutPMT2" here, since it's not a  WCSimWCTriggerBase (and actually it was causing the simulation to crash). But this should be confirmed. 

One critical point for the radon generator is that we need to compile with cmake, not with make, and the current script (like WCSim_hybrid.sh) need to be modified for this (maybe it would be good to have a script to do the compilation). We should also check everyone can use cmake (and know how to do). We also need to use Geant4.10.2 and higher versions.

Regarding CMAKE on sukap, its a bit tricky. I'm using this script:
```

#!/bin/bash

source G4ROOTsource.sh

/usr/local/cmake-3.4.3/bin/cmake --version 

curpath=${PWD}

name=WCSim_hybridPMT

if [ ! -d ../${name}-build ]; then

	echo "Creating libWCSimRoot.so"
	rm -f src/*Dict*
	make shared
	rm -f src/*Dict*
	
	echo "Creating build directory ../${name}-build"
	mkdir -p ../${name}-build
	
	cd ../${name}-build
	/usr/local/cmake-3.4.3/bin/cmake -DCMAKE_PREFIX_PATH=${G4INSTALLDIR} $curpath
	
	# Add needed directory and files
	ln -s $curpath/include ../${name}-build/include
	cp $curpath/biasprofile.dat ../${name}-build/.
else 
	cd ../${name}-build
fi


if [ -d ../${name}-build ]; then
	rm -f src/*Dict*
	make clean
	make -j7

	cd $curpath
fi	
```

### CODE REVIEW

**Comment by gpronost** [comment]
Sorry, I had some trouble to select the correct branch to merge

**Comment by bquilain** [comment]
Hi Guillaume.

It seems very nice on the code-side. Trying to compile it with cmake, could you tell me which ROOT and G4 install you used on sukap?

**Comment by gpronost** [comment]
Hi Benjamin,

I guess it's too late now, I will make a script with default locations for sukap.

**Comment by bquilain** [comment]
Thank you Guillaume!

**Pull request merged**
