### PR TITLE
Merging hybridPMT to nuPRISM/develop

### PR DESCRIPTION
**Pull request by pdeperio**
This is an example PR for merging to nuPRISM, after https://github.com/bquilain/WCSim/pull/11 is merged.

Note: I'm not sure if `hybridPMT` is your latest branch you're actually working from. If not, just edit the branch above ^

Here is where we should have several people read through the [Files changed](https://github.com/bquilain/WCSim/pull/12/files) and leave line-by-line comments to verify everything.

### CODE REVIEW

**Comment by bquilain** [comment]
Hi @nickwp and @pdeperio . I noticed the E61 branch does not apply any time smearing in WCSimWCPMT.cc . Has it been deported somewhere else?

**Comment by nickwp** [comment]
> Hi @nickwp and @pdeperio . I noticed the E61 branch does not apply any time smearing in WCSimWCPMT.cc . Has it been deported somewhere else?

I think @akutsuR is now the expert on WCSim things related to digitizing, but the time smearing appears to be applied [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimWCDigitizer.cc#L300) and [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimWCDigitizer.cc#L350) in WCSimWCDigitizer.cc
And the code for the actual smearing algorithm depends on PMT type in WCSimPMTObject.cc e.g. [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimPMTObject.cc#L2147-L2155) for the 3 inch PMT object we use.

But actually this appears to be the same in the 'official' branch ([here](https://github.com/WCSim/WCSim/blob/develop/src/WCSimWCDigitizer.cc#L316) and [here](https://github.com/WCSim/WCSim/blob/develop/src/WCSimWCDigitizer.cc#L366) in WCSimWCDigitizer.cc)?

**Comment by akutsuR** [comment]
> > Hi @nickwp and @pdeperio . I noticed the E61 branch does not apply any time smearing in WCSimWCPMT.cc . Has it been deported somewhere else?
> 
> I think @akutsuR is now the expert on WCSim things related to digitizing, but the time smearing appears to be applied [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimWCDigitizer.cc#L300) and [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimWCDigitizer.cc#L350) in WCSimWCDigitizer.cc
> And the code for the actual smearing algorithm depends on PMT type in WCSimPMTObject.cc e.g. [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimPMTObject.cc#L2147-L2155) for the 3 inch PMT object we use.
> 
> But actually this appears to be the same in the 'official' branch ([here](https://github.com/WCSim/WCSim/blob/develop/src/WCSimWCDigitizer.cc#L316) and [here](https://github.com/WCSim/WCSim/blob/develop/src/WCSimWCDigitizer.cc#L366) in WCSimWCDigitizer.cc)?

Hi, @nickwp 's understanding is correct. For the IWCD, the timing smearing is applied there. The PMT type that @nickwp mentioned is also correct. We have used that one. 

If I correctly understand, the current timing smearing is applied to the observed charge, so applying it in [WCSimWCDigitizerSKI::DigitizeHits](https://github.com/nuPRISM/WCSim/blob/3c883c47c0fc170be84b6fcea7bff7597af34170/src/WCSimWCDigitizer.cc#L192) rather than in [WCSimWCPMT::MakePeCorrection](https://github.com/nuPRISM/WCSim/blob/3c883c47c0fc170be84b6fcea7bff7597af34170/src/WCSimWCPMT.cc#L87)  seems to reasonable. Note that in [WCSimWCPMT::MakePeCorrection](https://github.com/nuPRISM/WCSim/blob/3c883c47c0fc170be84b6fcea7bff7597af34170/src/WCSimWCPMT.cc#L87) we do not have observed charge (i.e. sum of each true hit's charge) and do have charge for a pe. only. Of course, if we adopt another digitization model, which starts from a waveform simulation, then we may want to apply the smearing in [WCSimWCPMT::MakePeCorrection](https://github.com/nuPRISM/WCSim/blob/3c883c47c0fc170be84b6fcea7bff7597af34170/src/WCSimWCPMT.cc#L87)

**Comment by bquilain** [comment]
> > > Hi @nickwp and @pdeperio . I noticed the E61 branch does not apply any time smearing in WCSimWCPMT.cc . Has it been deported somewhere else?
> > 
> > 
> > I think @akutsuR is now the expert on WCSim things related to digitizing, but the time smearing appears to be applied [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimWCDigitizer.cc#L300) and [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimWCDigitizer.cc#L350) in WCSimWCDigitizer.cc
> > And the code for the actual smearing algorithm depends on PMT type in WCSimPMTObject.cc e.g. [here](https://github.com/nuPRISM/WCSim/blob/nuPRISM/develop/src/WCSimPMTObject.cc#L2147-L2155) for the 3 inch PMT object we use.
> > But actually this appears to be the same in the 'official' branch ([here](https://github.com/WCSim/WCSim/blob/develop/src/WCSimWCDigitizer.cc#L316) and [here](https://github.com/WCSim/WCSim/blob/develop/src/WCSimWCDigitizer.cc#L366) in WCSimWCDigitizer.cc)?
> 
> Hi, @nickwp 's understanding is correct. For the IWCD, the timing smearing is applied there. The PMT type that @nickwp mentioned is also correct. We have used that one.
> 
> If I correctly understand, the current timing smearing is applied to the observed charge, so applying it in [WCSimWCDigitizerSKI::DigitizeHits](https://github.com/nuPRISM/WCSim/blob/3c883c47c0fc170be84b6fcea7bff7597af34170/src/WCSimWCDigitizer.cc#L192) rather than in [WCSimWCPMT::MakePeCorrection](https://github.com/nuPRISM/WCSim/blob/3c883c47c0fc170be84b6fcea7bff7597af34170/src/WCSimWCPMT.cc#L87) seems to reasonable. Note that in [WCSimWCPMT::MakePeCorrection](https://github.com/nuPRISM/WCSim/blob/3c883c47c0fc170be84b6fcea7bff7597af34170/src/WCSimWCPMT.cc#L87) we do not have observed charge (i.e. sum of each true hit's charge) and do have charge for a pe. only. Of course, if we adopt another digitization model, which starts from a waveform simulation, then we may want to apply the smearing in [WCSimWCPMT::MakePeCorrection](https://github.com/nuPRISM/WCSim/blob/3c883c47c0fc170be84b6fcea7bff7597af34170/src/WCSimWCPMT.cc#L87)

Hi @nickwp and @akutsuR . Thank you very much for your answer. Yes, it appears to be the same in the official branch. I basically agree with @akutsuR point about where to let the smearing happen: it is entirely up to the way of modelling it, and in regard of the method we are using now (derived from observed charge measurement), it would be better to have it in the digitizer. What I am only worried, is that naively, someone not using the digitiser class may think that the PMT output will be the information he/she uses. Unfortunately, it would be entirely wrong. Ideally (i.e. in future), we would have the digtisation model @akutsuR described, which allows to keep the smearing in the "PMT part". For now, I will change it to what you have in main branch, this is clearly the most correct. Thank you very much!

**Comment by pdeperio** [comment]
so it looks like this merge is huge as expected. Do you all want to break it up into smaller PRs by grouping files together? Or just divide and conquer this one (starting with the conflict resolutions)?

**Comment by bquilain** [comment]
> so it looks like this merge is huge as expected. Do you all want to break it up into smaller PRs by grouping files together? Or just divide and conquer this one (starting with the conflict resolutions)?

Hi @pdeperio . It is indeed huge, but I would like to use the "divide and conquer" method as much as possible first :). So far, the differences affects different part of the code (digital part affecting late events, time smearing, geometry definition), so it could be easily debugged separately (looking at event display, timing distributions or focusing on late events). If I start to see degenerated problems, I will definitely split the PR, and will let you know here :)

**Comment by bquilain** [comment]
Hi @nickwp @akutsuR and @pdeperio . The merging has progressed so far smoothly for pmt type, digitizer, dark rate, trigger, root outputs. I am now tackling the final two parts: generator (esp. nuance format related) and detector construction. On the latter, I observed you got rid of the external mPMT reflector size parameters (size, angle, position) in WCSimConstructPMT.cc. They are pretty useful to do some optimisation study. Could you let me know if they are used somewhere else in the code?

**Comment by bquilain** [comment]
> Hi @nickwp @akutsuR and @pdeperio . The merging has progressed so far smoothly for pmt type, digitizer, dark rate, trigger, root outputs. I am now tackling the final two parts: generator (esp. nuance format related) and detector construction. On the latter, I observed you got rid of the external mPMT reflector size parameters (size, angle, position) in WCSimConstructPMT.cc. They are pretty useful to do some optimisation study. Could you let me know if they are used somewhere else in the code?

I am sorry, I should have been more accurate: this is not the reflector which is changed, but the way the reflector holder is calculated. The holder is now, not dependent anymore from the reflector size in nuPRISM branch.

**Comment by gpronost** [comment]
Hi, just one point about WCSimWCPMT, I am not sure how you want to merge, but if nuPrism version is used as default, I think it's important to keep the RelativeTiming option (specially for radioactivity decay simulation).

**Comment by bquilain** [comment]
> Hi, just one point about WCSimWCPMT, I am not sure how you want to merge, but if nuPrism version is used as default, I think it's important to keep the RelativeTiming option (specially for radioactivity decay simulation).

Thank you very much @gpronost . Actually, I finished the merging locally, and indeed kept the RelativeTiming option unchanged. I should confirm it after executing the code though, as some of the merging was automatic, I am always affraid something suspicious may have happened :)

**Comment by pdeperio** [comment]
finished?? do you need a review from @nickwp and @akutsuR ?

**Comment by bquilain** [comment]
Hi @pdeperio . I was opening the PR on nuPRISM repository and ask the review from @nickwp and @akutsuR . If you believe this is better doing it here, perfect for me!

**Comment by bquilain** [comment]
Here is what I was writing on the nuPRISM repo for PR:
This pull request contains the complete nuPRISM and hybrid merging done on my local fork. It basically contains:
-Possibility to have two types of PMT at construction.
-If several type of PMTs are used, have separated digitisers, dark rate, and triggers for each type.
-Radon generator is added.
-All float are converted to double.
-Very small change on the shape of the PMT holder in WCSimConstructPMT.cc.

**Comment by pdeperio** [comment]
yep sorry, you're right. i went ahead and did that just now! https://github.com/nuPRISM/WCSim/pull/61

go ahead and add your description in comments

**Comment by bquilain** [comment]
Aha, too quick. Ok, so let me just comment there then. Thank you @pdeperio !

**Pull request merged**
