### PR TITLE
Sync nuPRISM with bquilain

### PR DESCRIPTION
**Pull request by pdeperio**
Sync nuPRISM with bquilain for creating base for bigger merge of hybridPMT, etc.

### CODE REVIEW

**Comment by pdeperio** [comment]
although there are no conflicts, it would be good if those doing merge (e.g. @bquilain, @nickwp) can familiarize with all the commits/PRs above in case of later conflicts/interferences in big merge.

**Comment by nickwp** [comment]
Sorry, I'm a bit confused. This contains commits dating back to 2016, which are already included in the HybridPMT branch we want to eventually merge. So I'm not sure this is helpful to go through a load of commits, most of which are already in both branches we want to merge anyway?
Shouldn't we just be looking at the differences between the two branches we want to merge (bquilain/HybridPMT and nuPRISM/nuPRISM/develop), not this other branch (bquilain/nuPRISM/develop) that is older than both of them?

**Comment by pdeperio** [comment]
yep, just sent an email. was thinking to use `bquilain:nuPRISM/develop` as a base in case there are further necessary changes with merging `bquilain/hybridPMT`. 

so @bquilain can just go ahead and merge this i think and then start working from https://github.com/bquilain/WCSim/pull/12

**Comment by nickwp** [comment]
ok, that makes sense, thanks

**Comment by bquilain** [comment]
Thank you very much @pdeperio and @nickwp . I'll go ahead with this first set of sync, then proceed to 2nd step this week :)

**Pull request merged**
