### PR TITLE
New Trigger class, "NoTrigger" for n-tagging study

### PR DESCRIPTION
**Pull request by shotaizu**
I added new WCTrigger class, called "NoTrigger", which is used for n-tagging study. This code is implemented in the mainstream WCSim/WCSim. And I brought them into this hybrid-WCSim.

In addition, I merged RadonHybrid branch also. Therefore, I think it is better that first we merge "RadonHybrid" branch, and then merge this.

### CODE REVIEW

**Comment by shotaizu** [comment]
I found non-required time bias. I will remove this.

**Comment by shotaizu** [comment]
Now ready to be merged.

New features from me:
- Trigger class: "NoTrigger"
- Histograms in sample-script "AnalyzeWSHierarchy"
  - Event Vertex of XY, R2Z
- WCSim mac-file command: /DarkRate/SetDarkRate2 & /DarkRate/SetConvert2 in order to change darkrate of 3 inch PMTs via mac-file

**Review by gpronost — APPROVED** [review]
I solved the conflicts, the modifications are very nice!

**Comment by bquilain** [comment]
The updates are very nice:
-The comments you put in the code are quite helpful for new users.
-Possibility to modify the second PMT type characteristics from mac file is finally there, thank you very much for having added it!
-The new no trigger class is capital for n-tagging.
Thank you very much. I will test this now

**Comment by bquilain** [comment]
Just to say that I tested your new release, it works very nicely

**Pull request merged**
